services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - .env
    environment:
      - ENVIRONMENT=production
      - FRONTEND_URL=http://127.0.0.1
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - telegram-dashboard

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://127.0.0.1:8000/api
        - VITE_TELEGRAM_BOT_USERNAME=DashBoardMetricksBot
    ports:
      - "127.0.0.1:80:80"
    restart: unless-stopped
    networks:
      - telegram-dashboard

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - telegram-dashboard

networks:
  telegram-dashboard:
    driver: bridge

volumes:
  redis_data: