services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - ENVIRONMENT=production
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - telegram-dashboard

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:8000/api
    restart: unless-stopped
    networks:
      - telegram-dashboard

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - telegram-dashboard

networks:
  telegram-dashboard:
    driver: bridge

volumes:
  redis_data: